name: Client Is Buildable

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-client:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4
        
      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install client dependencies
      - name: Install dependencies in client/
        run: |
          cd client
          npm install

      # Start the client
      - name: Start Client
        run: | 
          cd client
          nohup npm start &  # Start the client in the background
          sleep 15           # Wait for 15 seconds to ensure it's running

      # Verify if the client is running on port 8081
      - name: Verify Client is Running
        run: |
          if ! lsof -i :8081 > /dev/null; then
            echo "Client did not start or crashed (nothing is listening on port 8081)"
            exit 1
          fi
